//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyAnalysisForDynamo.CEAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oListProjects")]
    public interface IGBS_oListProjects {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oListProjects/GBS_oListProjects", ReplyAction="http://tempuri.org/IGBS_oListProjects/GBS_oListProjectsResponse")]
        string GBS_oListProjects(string accessToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oListProjectsChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oListProjects, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oListProjectsClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oListProjects>, EnergyAnalysisForDynamo.CEAService.IGBS_oListProjects {
        
        public GBS_oListProjectsClient() {
        }
        
        public GBS_oListProjectsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oListProjectsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oListProjectsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oListProjectsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oListProjects(string accessToken) {
            return base.Channel.GBS_oListProjects(accessToken);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oListRuns")]
    public interface IGBS_oListRuns {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oListRuns/GBS_oListRuns", ReplyAction="http://tempuri.org/IGBS_oListRuns/GBS_oListRunsResponse")]
        string GBS_oListRuns(string accessToken, int projectId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oListRunsChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oListRuns, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oListRunsClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oListRuns>, EnergyAnalysisForDynamo.CEAService.IGBS_oListRuns {
        
        public GBS_oListRunsClient() {
        }
        
        public GBS_oListRunsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oListRunsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oListRunsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oListRunsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oListRuns(string accessToken, int projectId) {
            return base.Channel.GBS_oListRuns(accessToken, projectId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oNewRun")]
    public interface IGBS_oNewRun {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oNewRun/GBS_oNewRun", ReplyAction="http://tempuri.org/IGBS_oNewRun/GBS_oNewRunResponse")]
        string GBS_oNewRun(string accessToken, string title, int projectId, string zegbXML, ref int runID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oNewRunChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oNewRun, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oNewRunClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oNewRun>, EnergyAnalysisForDynamo.CEAService.IGBS_oNewRun {
        
        public GBS_oNewRunClient() {
        }
        
        public GBS_oNewRunClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oNewRunClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oNewRunClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oNewRunClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oNewRun(string accessToken, string title, int projectId, string zegbXML, ref int runID) {
            return base.Channel.GBS_oNewRun(accessToken, title, projectId, zegbXML, ref runID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oNewRunWithUtilityData")]
    public interface IGBS_oNewRunWithUtilityData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oNewRunWithUtilityData/GBS_oNewRunWithUtilityData", ReplyAction="http://tempuri.org/IGBS_oNewRunWithUtilityData/GBS_oNewRunWithUtilityDataResponse" +
            "")]
        string GBS_oNewRunWithUtilityData(string accessToken, string title, int projectId, string zegbXML, string utilityBillId, ref int runId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oNewRunWithUtilityDataChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oNewRunWithUtilityData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oNewRunWithUtilityDataClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oNewRunWithUtilityData>, EnergyAnalysisForDynamo.CEAService.IGBS_oNewRunWithUtilityData {
        
        public GBS_oNewRunWithUtilityDataClient() {
        }
        
        public GBS_oNewRunWithUtilityDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oNewRunWithUtilityDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oNewRunWithUtilityDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oNewRunWithUtilityDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oNewRunWithUtilityData(string accessToken, string title, int projectId, string zegbXML, string utilityBillId, ref int runId) {
            return base.Channel.GBS_oNewRunWithUtilityData(accessToken, title, projectId, zegbXML, utilityBillId, ref runId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oCreateProject")]
    public interface IGBS_oCreateProject {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oCreateProject/GBS_oCreateProject", ReplyAction="http://tempuri.org/IGBS_oCreateProject/GBS_oCreateProjectResponse")]
        int GBS_oCreateProject(string accessToken, string Title, string Demo, string BuildingTypeID, string ScheduleID, string Latitude, string Longitude, string ProjLicense, string WeatherID, string WeatherYear, string ElecCost, string FuelCost, string CultureInfo, ref string errorInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oCreateProjectChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oCreateProject, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oCreateProjectClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oCreateProject>, EnergyAnalysisForDynamo.CEAService.IGBS_oCreateProject {
        
        public GBS_oCreateProjectClient() {
        }
        
        public GBS_oCreateProjectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oCreateProjectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oCreateProjectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oCreateProjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GBS_oCreateProject(string accessToken, string Title, string Demo, string BuildingTypeID, string ScheduleID, string Latitude, string Longitude, string ProjLicense, string WeatherID, string WeatherYear, string ElecCost, string FuelCost, string CultureInfo, ref string errorInfo) {
            return base.Channel.GBS_oCreateProject(accessToken, Title, Demo, BuildingTypeID, ScheduleID, Latitude, Longitude, ProjLicense, WeatherID, WeatherYear, ElecCost, FuelCost, CultureInfo, ref errorInfo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetRunStatus")]
    public interface IGBS_oGetRunStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetRunStatus/GBS_oGetRunStatus", ReplyAction="http://tempuri.org/IGBS_oGetRunStatus/GBS_oGetRunStatusResponse")]
        string GBS_oGetRunStatus(string accessToken, string RunID, string cultureInfoForMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetRunStatusChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetRunStatusClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunStatus>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunStatus {
        
        public GBS_oGetRunStatusClient() {
        }
        
        public GBS_oGetRunStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetRunStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetRunStatus(string accessToken, string RunID, string cultureInfoForMsg) {
            return base.Channel.GBS_oGetRunStatus(accessToken, RunID, cultureInfoForMsg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetRunStatusSettings")]
    public interface IGBS_oGetRunStatusSettings {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetRunStatusSettings/GBS_oGetRunStatusSettings", ReplyAction="http://tempuri.org/IGBS_oGetRunStatusSettings/GBS_oGetRunStatusSettingsResponse")]
        void GBS_oGetRunStatusSettings(ref int frequency, ref int timeout);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetRunStatusSettingsChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunStatusSettings, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetRunStatusSettingsClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunStatusSettings>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunStatusSettings {
        
        public GBS_oGetRunStatusSettingsClient() {
        }
        
        public GBS_oGetRunStatusSettingsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetRunStatusSettingsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunStatusSettingsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunStatusSettingsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GBS_oGetRunStatusSettings(ref int frequency, ref int timeout) {
            base.Channel.GBS_oGetRunStatusSettings(ref frequency, ref timeout);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetNearestWeatherStations")]
    public interface IGBS_oGetNearestWeatherStations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetNearestWeatherStations/GBS_oGetNearestWeatherStations" +
            "", ReplyAction="http://tempuri.org/IGBS_oGetNearestWeatherStations/GBS_oGetNearestWeatherStations" +
            "Response")]
        string GBS_oGetNearestWeatherStations(string accessToken, string latitude, string longitude, string count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetNearestWeatherStationsChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetNearestWeatherStations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetNearestWeatherStationsClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetNearestWeatherStations>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetNearestWeatherStations {
        
        public GBS_oGetNearestWeatherStationsClient() {
        }
        
        public GBS_oGetNearestWeatherStationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetNearestWeatherStationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetNearestWeatherStationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetNearestWeatherStationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetNearestWeatherStations(string accessToken, string latitude, string longitude, string count) {
            return base.Channel.GBS_oGetNearestWeatherStations(accessToken, latitude, longitude, count);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetWeatherChartsZipFile")]
    public interface IGBS_oGetWeatherChartsZipFile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetWeatherChartsZipFile/GBS_oGetWeatherChartsZipFile", ReplyAction="http://tempuri.org/IGBS_oGetWeatherChartsZipFile/GBS_oGetWeatherChartsZipFileResp" +
            "onse")]
        bool GBS_oGetWeatherChartsZipFile(string accessToken, string cultureInfo, string stationId, string isSIUnitType, ref string zippedChartFiles, ref string errorInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetWeatherChartsZipFileChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetWeatherChartsZipFile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetWeatherChartsZipFileClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetWeatherChartsZipFile>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetWeatherChartsZipFile {
        
        public GBS_oGetWeatherChartsZipFileClient() {
        }
        
        public GBS_oGetWeatherChartsZipFileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetWeatherChartsZipFileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetWeatherChartsZipFileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetWeatherChartsZipFileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GBS_oGetWeatherChartsZipFile(string accessToken, string cultureInfo, string stationId, string isSIUnitType, ref string zippedChartFiles, ref string errorInfo) {
            return base.Channel.GBS_oGetWeatherChartsZipFile(accessToken, cultureInfo, stationId, isSIUnitType, ref zippedChartFiles, ref errorInfo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetChartsURL")]
    public interface IGBS_oGetChartsURL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetChartsURL/GBS_oGetChartsURL", ReplyAction="http://tempuri.org/IGBS_oGetChartsURL/GBS_oGetChartsURLResponse")]
        bool GBS_oGetChartsURL(string accessToken, string RunID, string cultureInfo, string isSIUnitType, ref string urlReturn, ref string errorInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetChartsURLChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetChartsURL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetChartsURLClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetChartsURL>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetChartsURL {
        
        public GBS_oGetChartsURLClient() {
        }
        
        public GBS_oGetChartsURLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetChartsURLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetChartsURLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetChartsURLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GBS_oGetChartsURL(string accessToken, string RunID, string cultureInfo, string isSIUnitType, ref string urlReturn, ref string errorInfo) {
            return base.Channel.GBS_oGetChartsURL(accessToken, RunID, cultureInfo, isSIUnitType, ref urlReturn, ref errorInfo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetAnalysisInfoByCurrentUser")]
    public interface IGBS_oGetAnalysisInfoByCurrentUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetAnalysisInfoByCurrentUser/GBS_oGetAnalysisInfoByCurre" +
            "ntUser", ReplyAction="http://tempuri.org/IGBS_oGetAnalysisInfoByCurrentUser/GBS_oGetAnalysisInfoByCurre" +
            "ntUserResponse")]
        string GBS_oGetAnalysisInfoByCurrentUser(string accessToken, ref string errorInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetAnalysisInfoByCurrentUserChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetAnalysisInfoByCurrentUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetAnalysisInfoByCurrentUserClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetAnalysisInfoByCurrentUser>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetAnalysisInfoByCurrentUser {
        
        public GBS_oGetAnalysisInfoByCurrentUserClient() {
        }
        
        public GBS_oGetAnalysisInfoByCurrentUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetAnalysisInfoByCurrentUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetAnalysisInfoByCurrentUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetAnalysisInfoByCurrentUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetAnalysisInfoByCurrentUser(string accessToken, ref string errorInfo) {
            return base.Channel.GBS_oGetAnalysisInfoByCurrentUser(accessToken, ref errorInfo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetProjectInvariants")]
    public interface IGBS_oGetProjectInvariants {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetProjectInvariants/GBS_oGetProjectInvariants", ReplyAction="http://tempuri.org/IGBS_oGetProjectInvariants/GBS_oGetProjectInvariantsResponse")]
        bool GBS_oGetProjectInvariants(string accessToken, string ProjectID, ref string Title, ref string Demo, ref string BuildingTypeIDg, ref string ScheduleID, ref string Latitude, ref string Longitude, ref string WeatherID, ref string ElecCost, ref string FuelCost, ref string CultureInfo, ref string errorInfo, string cultureInfoForMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetProjectInvariantsChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetProjectInvariants, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetProjectInvariantsClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetProjectInvariants>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetProjectInvariants {
        
        public GBS_oGetProjectInvariantsClient() {
        }
        
        public GBS_oGetProjectInvariantsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetProjectInvariantsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetProjectInvariantsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetProjectInvariantsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GBS_oGetProjectInvariants(string accessToken, string ProjectID, ref string Title, ref string Demo, ref string BuildingTypeIDg, ref string ScheduleID, ref string Latitude, ref string Longitude, ref string WeatherID, ref string ElecCost, ref string FuelCost, ref string CultureInfo, ref string errorInfo, string cultureInfoForMsg) {
            return base.Channel.GBS_oGetProjectInvariants(accessToken, ProjectID, ref Title, ref Demo, ref BuildingTypeIDg, ref ScheduleID, ref Latitude, ref Longitude, ref WeatherID, ref ElecCost, ref FuelCost, ref CultureInfo, ref errorInfo, cultureInfoForMsg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oUpdateProjectHVACSystemByID")]
    public interface IGBS_oUpdateProjectHVACSystemByID {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oUpdateProjectHVACSystemByID/GBS_oUpdateProjectHVACSystem" +
            "ByID", ReplyAction="http://tempuri.org/IGBS_oUpdateProjectHVACSystemByID/GBS_oUpdateProjectHVACSystem" +
            "ByIDResponse")]
        bool GBS_oUpdateProjectHVACSystemByID(string accessToken, string ProjectID, string HVACID, ref string errorInfo, string cultureInfoForMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oUpdateProjectHVACSystemByIDChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oUpdateProjectHVACSystemByID, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oUpdateProjectHVACSystemByIDClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oUpdateProjectHVACSystemByID>, EnergyAnalysisForDynamo.CEAService.IGBS_oUpdateProjectHVACSystemByID {
        
        public GBS_oUpdateProjectHVACSystemByIDClient() {
        }
        
        public GBS_oUpdateProjectHVACSystemByIDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oUpdateProjectHVACSystemByIDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oUpdateProjectHVACSystemByIDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oUpdateProjectHVACSystemByIDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GBS_oUpdateProjectHVACSystemByID(string accessToken, string ProjectID, string HVACID, ref string errorInfo, string cultureInfoForMsg) {
            return base.Channel.GBS_oUpdateProjectHVACSystemByID(accessToken, ProjectID, HVACID, ref errorInfo, cultureInfoForMsg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetResultSettingFiles")]
    public interface IGBS_oGetResultSettingFiles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetResultSettingFiles/GBS_oGetResultSettingFiles", ReplyAction="http://tempuri.org/IGBS_oGetResultSettingFiles/GBS_oGetResultSettingFilesResponse" +
            "")]
        bool GBS_oGetResultSettingFiles(string accessToken, string cultureInfo, ref string zippedSettingFiles, ref string errorInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetResultSettingFilesChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetResultSettingFiles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetResultSettingFilesClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetResultSettingFiles>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetResultSettingFiles {
        
        public GBS_oGetResultSettingFilesClient() {
        }
        
        public GBS_oGetResultSettingFilesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetResultSettingFilesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetResultSettingFilesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetResultSettingFilesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GBS_oGetResultSettingFiles(string accessToken, string cultureInfo, ref string zippedSettingFiles, ref string errorInfo) {
            return base.Channel.GBS_oGetResultSettingFiles(accessToken, cultureInfo, ref zippedSettingFiles, ref errorInfo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oRenameProject")]
    public interface IGBS_oRenameProject {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oRenameProject/GBS_oRenameProject", ReplyAction="http://tempuri.org/IGBS_oRenameProject/GBS_oRenameProjectResponse")]
        bool GBS_oRenameProject(string accessToken, string ProjectID, string NewTitle, ref string errorInfo, string cultureInfoForMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oRenameProjectChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oRenameProject, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oRenameProjectClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oRenameProject>, EnergyAnalysisForDynamo.CEAService.IGBS_oRenameProject {
        
        public GBS_oRenameProjectClient() {
        }
        
        public GBS_oRenameProjectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oRenameProjectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oRenameProjectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oRenameProjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GBS_oRenameProject(string accessToken, string ProjectID, string NewTitle, ref string errorInfo, string cultureInfoForMsg) {
            return base.Channel.GBS_oRenameProject(accessToken, ProjectID, NewTitle, ref errorInfo, cultureInfoForMsg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oRenameRun")]
    public interface IGBS_oRenameRun {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oRenameRun/GBS_oRenameRun", ReplyAction="http://tempuri.org/IGBS_oRenameRun/GBS_oRenameRunResponse")]
        bool GBS_oRenameRun(string accessToken, string RunID, string NewTitle, ref string errorInfo, string cultureInfoForMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oRenameRunChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oRenameRun, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oRenameRunClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oRenameRun>, EnergyAnalysisForDynamo.CEAService.IGBS_oRenameRun {
        
        public GBS_oRenameRunClient() {
        }
        
        public GBS_oRenameRunClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oRenameRunClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oRenameRunClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oRenameRunClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GBS_oRenameRun(string accessToken, string RunID, string NewTitle, ref string errorInfo, string cultureInfoForMsg) {
            return base.Channel.GBS_oRenameRun(accessToken, RunID, NewTitle, ref errorInfo, cultureInfoForMsg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetResultSettingVersion")]
    public interface IGBS_oGetResultSettingVersion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetResultSettingVersion/GBS_oGetResultSettingVersion", ReplyAction="http://tempuri.org/IGBS_oGetResultSettingVersion/GBS_oGetResultSettingVersionResp" +
            "onse")]
        bool GBS_oGetResultSettingVersion(string accessToken, string cultureInfo, ref string version, ref string errorInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetResultSettingVersionChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetResultSettingVersion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetResultSettingVersionClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetResultSettingVersion>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetResultSettingVersion {
        
        public GBS_oGetResultSettingVersionClient() {
        }
        
        public GBS_oGetResultSettingVersionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetResultSettingVersionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetResultSettingVersionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetResultSettingVersionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GBS_oGetResultSettingVersion(string accessToken, string cultureInfo, ref string version, ref string errorInfo) {
            return base.Channel.GBS_oGetResultSettingVersion(accessToken, cultureInfo, ref version, ref errorInfo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oUploadFiles")]
    public interface IGBS_oUploadFiles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oUploadFiles/GBS_oUploadFiles", ReplyAction="http://tempuri.org/IGBS_oUploadFiles/GBS_oUploadFilesResponse")]
        bool GBS_oUploadFiles(string accessToken, int runId, string zipFile, ref string errorInfo, string cultureInfoForMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oUploadFilesChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oUploadFiles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oUploadFilesClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oUploadFiles>, EnergyAnalysisForDynamo.CEAService.IGBS_oUploadFiles {
        
        public GBS_oUploadFilesClient() {
        }
        
        public GBS_oUploadFilesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oUploadFilesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oUploadFilesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oUploadFilesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GBS_oUploadFiles(string accessToken, int runId, string zipFile, ref string errorInfo, string cultureInfoForMsg) {
            return base.Channel.GBS_oUploadFiles(accessToken, runId, zipFile, ref errorInfo, cultureInfoForMsg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetLatestCeaVersion")]
    public interface IGBS_oGetLatestCeaVersion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetLatestCeaVersion/GBS_oGetLatestCeaVersion", ReplyAction="http://tempuri.org/IGBS_oGetLatestCeaVersion/GBS_oGetLatestCeaVersionResponse")]
        string GBS_oGetLatestCeaVersion(string accessToken, string appIdentity, string localeIdentifier, ref string errorInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetLatestCeaVersionChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetLatestCeaVersion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetLatestCeaVersionClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetLatestCeaVersion>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetLatestCeaVersion {
        
        public GBS_oGetLatestCeaVersionClient() {
        }
        
        public GBS_oGetLatestCeaVersionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetLatestCeaVersionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetLatestCeaVersionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetLatestCeaVersionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetLatestCeaVersion(string accessToken, string appIdentity, string localeIdentifier, ref string errorInfo) {
            return base.Channel.GBS_oGetLatestCeaVersion(accessToken, appIdentity, localeIdentifier, ref errorInfo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetVersionFiles")]
    public interface IGBS_oGetVersionFiles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetVersionFiles/GBS_oGetVersionFiles", ReplyAction="http://tempuri.org/IGBS_oGetVersionFiles/GBS_oGetVersionFilesResponse")]
        string GBS_oGetVersionFiles(string identifier, ref string errorInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetVersionFilesChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetVersionFiles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetVersionFilesClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetVersionFiles>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetVersionFiles {
        
        public GBS_oGetVersionFilesClient() {
        }
        
        public GBS_oGetVersionFilesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetVersionFilesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetVersionFilesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetVersionFilesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetVersionFiles(string identifier, ref string errorInfo) {
            return base.Channel.GBS_oGetVersionFiles(identifier, ref errorInfo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetRunEnergySimulationDialog")]
    public interface IGBS_oGetRunEnergySimulationDialog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetRunEnergySimulationDialog/GBS_oGetRunEnergySimulation" +
            "Dialog", ReplyAction="http://tempuri.org/IGBS_oGetRunEnergySimulationDialog/GBS_oGetRunEnergySimulation" +
            "DialogResponse")]
        string GBS_oGetRunEnergySimulationDialog(string accessToken, ref string errorInfo, string culture, int maxBytesInResponse);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetRunEnergySimulationDialogChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunEnergySimulationDialog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetRunEnergySimulationDialogClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunEnergySimulationDialog>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunEnergySimulationDialog {
        
        public GBS_oGetRunEnergySimulationDialogClient() {
        }
        
        public GBS_oGetRunEnergySimulationDialogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetRunEnergySimulationDialogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunEnergySimulationDialogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunEnergySimulationDialogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetRunEnergySimulationDialog(string accessToken, ref string errorInfo, string culture, int maxBytesInResponse) {
            return base.Channel.GBS_oGetRunEnergySimulationDialog(accessToken, ref errorInfo, culture, maxBytesInResponse);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetRunEnergySimulationDialogExistingProjectsPage")]
    public interface IGBS_oGetRunEnergySimulationDialogExistingProjectsPage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetRunEnergySimulationDialogExistingProjectsPage/GBS_oGe" +
            "tRunEnergySimulationDialogExistingProjectsPage", ReplyAction="http://tempuri.org/IGBS_oGetRunEnergySimulationDialogExistingProjectsPage/GBS_oGe" +
            "tRunEnergySimulationDialogExistingProjectsPageResponse")]
        string GBS_oGetRunEnergySimulationDialogExistingProjectsPage(string accessToken, ref string errorInfo, string culture, int nToSkip, int maxBytesInResponse);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetRunEnergySimulationDialogExistingProjectsPageChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunEnergySimulationDialogExistingProjectsPage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetRunEnergySimulationDialogExistingProjectsPageClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunEnergySimulationDialogExistingProjectsPage>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunEnergySimulationDialogExistingProjectsPage {
        
        public GBS_oGetRunEnergySimulationDialogExistingProjectsPageClient() {
        }
        
        public GBS_oGetRunEnergySimulationDialogExistingProjectsPageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetRunEnergySimulationDialogExistingProjectsPageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunEnergySimulationDialogExistingProjectsPageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunEnergySimulationDialogExistingProjectsPageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetRunEnergySimulationDialogExistingProjectsPage(string accessToken, ref string errorInfo, string culture, int nToSkip, int maxBytesInResponse) {
            return base.Channel.GBS_oGetRunEnergySimulationDialogExistingProjectsPage(accessToken, ref errorInfo, culture, nToSkip, maxBytesInResponse);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetRunEnergySimulationDialogUtilityDataPage")]
    public interface IGBS_oGetRunEnergySimulationDialogUtilityDataPage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetRunEnergySimulationDialogUtilityDataPage/GBS_oGetRunE" +
            "nergySimulationDialogUtilityDataPage", ReplyAction="http://tempuri.org/IGBS_oGetRunEnergySimulationDialogUtilityDataPage/GBS_oGetRunE" +
            "nergySimulationDialogUtilityDataPageResponse")]
        string GBS_oGetRunEnergySimulationDialogUtilityDataPage(string accessToken, ref string errorInfo, string culture, int nToSkip, int projectId, int maxBytesInResponse);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetRunEnergySimulationDialogUtilityDataPageChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunEnergySimulationDialogUtilityDataPage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetRunEnergySimulationDialogUtilityDataPageClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunEnergySimulationDialogUtilityDataPage>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunEnergySimulationDialogUtilityDataPage {
        
        public GBS_oGetRunEnergySimulationDialogUtilityDataPageClient() {
        }
        
        public GBS_oGetRunEnergySimulationDialogUtilityDataPageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetRunEnergySimulationDialogUtilityDataPageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunEnergySimulationDialogUtilityDataPageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunEnergySimulationDialogUtilityDataPageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetRunEnergySimulationDialogUtilityDataPage(string accessToken, ref string errorInfo, string culture, int nToSkip, int projectId, int maxBytesInResponse) {
            return base.Channel.GBS_oGetRunEnergySimulationDialogUtilityDataPage(accessToken, ref errorInfo, culture, nToSkip, projectId, maxBytesInResponse);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetRunStatusClientToken")]
    public interface IGBS_oGetRunStatusClientToken {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetRunStatusClientToken/GBS_oGetRunStatusClientToken", ReplyAction="http://tempuri.org/IGBS_oGetRunStatusClientToken/GBS_oGetRunStatusClientTokenResp" +
            "onse")]
        string GBS_oGetRunStatusClientToken(string accessToken, string clientToken, string cultureInfoForMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetRunStatusClientTokenChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunStatusClientToken, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetRunStatusClientTokenClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunStatusClientToken>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunStatusClientToken {
        
        public GBS_oGetRunStatusClientTokenClient() {
        }
        
        public GBS_oGetRunStatusClientTokenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetRunStatusClientTokenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunStatusClientTokenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunStatusClientTokenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetRunStatusClientToken(string accessToken, string clientToken, string cultureInfoForMsg) {
            return base.Channel.GBS_oGetRunStatusClientToken(accessToken, clientToken, cultureInfoForMsg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oGetRunIdForClientToken")]
    public interface IGBS_oGetRunIdForClientToken {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oGetRunIdForClientToken/GBS_oGetRunIdForClientToken", ReplyAction="http://tempuri.org/IGBS_oGetRunIdForClientToken/GBS_oGetRunIdForClientTokenRespon" +
            "se")]
        string GBS_oGetRunIdForClientToken(string accessToken, string clientToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oGetRunIdForClientTokenChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunIdForClientToken, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oGetRunIdForClientTokenClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunIdForClientToken>, EnergyAnalysisForDynamo.CEAService.IGBS_oGetRunIdForClientToken {
        
        public GBS_oGetRunIdForClientTokenClient() {
        }
        
        public GBS_oGetRunIdForClientTokenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oGetRunIdForClientTokenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunIdForClientTokenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oGetRunIdForClientTokenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oGetRunIdForClientToken(string accessToken, string clientToken) {
            return base.Channel.GBS_oGetRunIdForClientToken(accessToken, clientToken);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.IGBS_oNewRunClientToken")]
    public interface IGBS_oNewRunClientToken {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGBS_oNewRunClientToken/GBS_oNewRunClientToken", ReplyAction="http://tempuri.org/IGBS_oNewRunClientToken/GBS_oNewRunClientTokenResponse")]
        string GBS_oNewRunClientToken(string accessToken, string title, int projectId, string zegbXML, ref int runID, string clientToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGBS_oNewRunClientTokenChannel : EnergyAnalysisForDynamo.CEAService.IGBS_oNewRunClientToken, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GBS_oNewRunClientTokenClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.IGBS_oNewRunClientToken>, EnergyAnalysisForDynamo.CEAService.IGBS_oNewRunClientToken {
        
        public GBS_oNewRunClientTokenClient() {
        }
        
        public GBS_oNewRunClientTokenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GBS_oNewRunClientTokenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oNewRunClientTokenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GBS_oNewRunClientTokenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GBS_oNewRunClientToken(string accessToken, string title, int projectId, string zegbXML, ref int runID, string clientToken) {
            return base.Channel.GBS_oNewRunClientToken(accessToken, title, projectId, zegbXML, ref runID, clientToken);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEAService.ISolon")]
    public interface ISolon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolon/GetSolonPackage", ReplyAction="http://tempuri.org/ISolon/GetSolonPackageResponse")]
        System.IO.Stream GetSolonPackage(string accessToken, int runId, bool isSIUnitType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolon/CheckSolonUpdate", ReplyAction="http://tempuri.org/ISolon/CheckSolonUpdateResponse")]
        bool CheckSolonUpdate(string accessToken, int dashboardId, int dashboardVersion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolonChannel : EnergyAnalysisForDynamo.CEAService.ISolon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolonClient : System.ServiceModel.ClientBase<EnergyAnalysisForDynamo.CEAService.ISolon>, EnergyAnalysisForDynamo.CEAService.ISolon {
        
        public SolonClient() {
        }
        
        public SolonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetSolonPackage(string accessToken, int runId, bool isSIUnitType) {
            return base.Channel.GetSolonPackage(accessToken, runId, isSIUnitType);
        }
        
        public bool CheckSolonUpdate(string accessToken, int dashboardId, int dashboardVersion) {
            return base.Channel.CheckSolonUpdate(accessToken, dashboardId, dashboardVersion);
        }
    }
}
